import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'kruna' at '10/29/16 10:21 AM' with Gradle 2.14.1
 *
 * @author kruna, @date 10/29/16 10:21 AM
 */
public class KafkaClientTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue(true);
    }
}
